language: python
python:
  - "3.7"

cache: pip

before_install:
  - pip install codecov

# command to install dependencies
install:
  - make install

# command to run tests
script:
  - make unit

after_success:
  # submit coverage
  codecov