language: python
python:
  - "3.7"

cache: pip

# command to install dependencies
install:
  - pip install coverage
  - pipenv lock -r --dev > requirements.txt
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov=libbisca

after_success:
  codecov
