language: python
python:
  - "3.7"

cache: pip

before_install:
  - pip install codecov

# command to install dependencies - TODO: check
install:
  - make init

# command to run tests - TODO: check
script:
  - make unit

after_success:
  # submit coverage
  codecov
